- name: Validate parameters
  ansible.builtin.assert:
    that:
      - epel_repo_url is string
      - epel_repo_gpg_key_url is string
      - epel_repofile_path is string
      - epel_repo_disable is boolean

- name: Include EPEL tasks
  ansible.builtin.import_tasks: "epel.yml"
  when: ansible_facts['os_family'] == "RedHat"
